= Rapport SAÉ 2.03 - Installation de services réseaux
Dewaele Enzo, Fernandes Bastien, Hamiti Edi. 2025 <<<
:toc:
:toc-title: Table des matières
:stylesheet: ./css/custom.css
:icons: font

== Question(s) 1. À propos de Gitea

*Qu’est-ce que Gitea ?*

Gitea est une plateforme de code source qui permet de créer, gérer et partager des dépôts Git via une interface web. C'est une alternative plus légère à des solutions comme Github ou Gitlab, permettant de s'auto-héberger et de gérer leurs propres dépôts sans dépendre d'une solution cloud

*Gitea peut être comparé à des logiciels comme (en citer au moins 2) ?*

. GitHub : Une plateforme populaire de gestion de code source basée sur Git, offrant des services comme la gestion de projets, des wikis, des discussions et plus encore.
. GitLab : Une autre plateforme similaire à GitHub, mais qui inclut aussi des fonctionnalités d'intégration continue (CI), de livraison continue (CD) et de gestion de pipelines DevOps.

*Qu’est-ce qu’un fork (dans le domaine du développement logiciel bien entendu) ?*

Un "fork" est une copie indépendante d'un projet existant. Dans le contexte des plateformes comme GitHub, un fork permet à un utilisateur de prendre un projet open-source, d'y apporter ses propres modifications sans affecter le projet original, et de soumettre ensuite ses changements sous forme de "pull requests" si nécessaire.

*De quel logiciel Gitea est-il le fork ? Ce logiciel existe-t-il encore ?*

Gitea est un fork du logiciel Gogs, une autre plateforme de gestion de dépôts Git. Gogs existe toujours, bien qu'il soit moins actif que Gitea, qui a connu une adoption plus large et une communauté plus dynamique.



== Question(s) 2. Mise à jour

*Donnez la version que vous avez installé et la commande permettant d’obtenir cette information.*

Pour obtenir la version de Gitea installée, on utilise la commande suivante :
[source, bash]
----
gitea --version
----

Nous avons la version 1.23.5 de Gitea.

*Comment faire pour mettre à jour le binaire de votre service sans devoir tout reconfigurer ?*

//J'ai un doute sur ça

Pour mettre à jour le binaire de Gitea sans reconfigurer tout le système, il suffit de télécharger la dernière version stable du binaire et de remplacer l'exécutable actuel par le nouveau, comme expliqué précédemment. Cette méthode permet de conserver toutes les configurations existantes, y compris les paramètres de base de données et les utilisateurs.

== Problèmes rencontrés durant l'installation

Durant l'installation de Gitea sur les machines virtuelles, nous avons rencontré une erreur avec les permissions du dossier `/etc/gitea`, qui ne permetter pas l'initialisation du fichier `app.ini`.


== Tests d'utilisation

=== Créations d'utilisateurs

Avant de créer des projets, on peut créer différents utilisateurs. Il y a plusieurs moyens de créer des utilisateurs sur Gitea :

[notoc]
==== En tant qu'administrateur

En tant qu'administrateur, il est possible d'aller dans la page d'administration du site et ensuite accéder à la page "User accounts" pour créer un utilisateurs

.Tutoriel pour accéder à la page de création d'utilisateur
video::video/admin_creation_user.mp4[]

[notoc]
==== En tant qu'utilisateur standard

On peut créer un compte sur la page d'accueil de Gitea elit sit elit ullamco tempor aute occaecat id consectetur amet.

.Tutoriel sur la création de comptes sans accès administrateur
video::video/admin_creation_user.mp4[]

=== Création de projets

> Réalisez l'ajout d'un projet directement créé depuis l’interface web de Gitea

Pour créer un projet directement en utilisant l'interface web de Gitea, nous avons cliqué sur le bouton "+" situé en haut à droite de l'interface puis sur "New repository". Nous avons ensuite rempli les informations nécessaires pour la création du projet.

